apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MreliotA/prometheus-policy-autoscaler.git
    targetRevision: main
    path: config/samples
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: laravel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
