{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Chart.Name) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}
